# Generated by Django 5.2.4 on 2025-07-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_show_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto_show',
            old_name='category',
            new_name='category_id',
        ),
    ]
