# Generated by Django 5.2.4 on 2025-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_auto_show_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_show',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
