# Generated by Django 5.2.4 on 2025-07-22 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_auto_show_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_show',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto_show',
            name='model_car',
            field=models.CharField(max_length=222),
        ),
        migrations.AlterField(
            model_name='auto_show',
            name='title',
            field=models.CharField(max_length=222),
        ),
    ]
